<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="SBR-DEVPQA-12" name="com.cm.qa.testcases.UsernamePageTests" tests="5" failures="0" timestamp="22 Jan 2020 06:59:41 GMT" time="0.009" errors="1">
  <testcase name="setUp" time="0.009" classname="com.cm.qa.testcases.UsernamePageTests">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at cm.cm.qa.base.TestBase.initializeBrowser(TestBase.java:66)
at com.cm.qa.testcases.UsernamePageTests.setUp(UsernamePageTests.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="usernameScreenCMLogoImageTest" time="0.000" classname="com.cm.qa.testcases.UsernamePageTests">
    <skipped/>
  </testcase> <!-- usernameScreenCMLogoImageTest -->
  <testcase name="blankUsernameTest" time="0.000" classname="com.cm.qa.testcases.UsernamePageTests">
    <skipped/>
  </testcase> <!-- blankUsernameTest -->
  <testcase name="verifyUserNameScreenFooterText" time="0.000" classname="com.cm.qa.testcases.UsernamePageTests">
    <skipped/>
  </testcase> <!-- verifyUserNameScreenFooterText -->
  <testcase name="validUsernameTest" time="0.000" classname="com.cm.qa.testcases.UsernamePageTests">
    <skipped/>
  </testcase> <!-- validUsernameTest -->
</testsuite> <!-- com.cm.qa.testcases.UsernamePageTests -->
